// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi demo-apis
GCPUG Tokyo DevOps Day September 2017 Demo API



    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
