package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "encoding/json"

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "GCPUG Tokyo DevOps Day September 2017 Demo API\n",
    "title": "demo-apis",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/api/v1",
  "paths": {
    "/version": {
      "get": {
        "description": "API バージョンの取得\n",
        "tags": [
          "services"
        ],
        "operationId": "getVersion",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Version"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Version": {
      "description": "バージョン情報",
      "required": [
        "version"
      ],
      "properties": {
        "version": {
          "description": "API バージョン",
          "type": "string"
        }
      }
    }
  }
}`))
}
